"""1.6.5: add renewal_decision field

Revision ID: 2e9359242a33
Revises: e2a4c6f8d0b1
Create Date: 2026-06-29 12:25:00.522885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9359242a33'
down_revision: Union[str, Sequence[str], None] = 'e2a4c6f8d0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_audit_log_tenant_vendor'), table_name='vendor_audit_log')
    op.drop_index(op.f('ix_vendor_audit_log_user_id'), table_name='vendor_audit_log')
    op.create_index(op.f('ix_vendor_audit_log_tenant_id'), 'vendor_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vendor_audit_log_vendor_id'), 'vendor_audit_log', ['vendor_id'], unique=False)
    op.add_column('vendors', sa.Column('renewal_decision', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'renewal_decision')
    op.drop_index(op.f('ix_vendor_audit_log_vendor_id'), table_name='vendor_audit_log')
    op.drop_index(op.f('ix_vendor_audit_log_tenant_id'), table_name='vendor_audit_log')
    op.create_index(op.f('ix_vendor_audit_log_user_id'), 'vendor_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_vendor_audit_log_tenant_vendor'), 'vendor_audit_log', ['tenant_id', 'vendor_id'], unique=False)
    # ### end Alembic commands ###
